package repohooks

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"

	"github.com/miradorlabs/terma-cli/internal/gitx"
)

// pre-commit moves a hook it replaces to <name>.legacy and runs it from there (migration
// mode); lefthook moves one to .old and never runs it.
const (
	legacySuffix    = ".legacy"
	preCommitHeader = "File generated by pre-commit"
)

// hookState is what git runs for one hook name, and whether terma's script is in it.
type hookState int

const (
	// hookAbsent: nothing at the name.
	hookAbsent hookState = iota
	// hookOurs: terma's script at the name.
	hookOurs
	// hookOther: another hook at the name, which an install sets aside.
	hookOther
	// hookViaTool: pre-commit's hook at the name runs terma's from .legacy: a working chain.
	hookViaTool
	// hookLooped: as hookViaTool, but terma's runs pre-commit's again: every commit fails.
	hookLooped
	// hookTaken: another hook at the name, not running terma's, and a different one set aside.
	hookTaken
)

// hook is one hook name's state, with the copy of terma's script a tool runs, if any.
type hook struct {
	state hookState
	copy  string // the path of terma's script under a tool's suffix
}

// stateOf reads the hook name in dir.
func stateOf(dir, name string) (hook, error) {
	path := filepath.Join(dir, name)
	there, present, err := found(path)
	switch {
	case err != nil:
		return hook{}, err
	case !present:
		return hook{state: hookAbsent}, nil
	case isOurs(there):
		return hook{state: hookOurs}, nil
	}
	// Only pre-commit's hook runs .legacy: a manager installed over it leaves a stale one.
	ours := ""
	if bytes.Contains(there, []byte(preCommitHeader)) {
		if data, present, err := found(path + legacySuffix); err == nil && present && isOurs(data) {
			ours = path + legacySuffix
		}
	}
	_, err = os.Lstat(path + preTermaSuffix)
	setAside := err == nil
	same := setAside && sameBytes(path, path+preTermaSuffix)
	switch {
	case ours != "" && same:
		return hook{state: hookLooped, copy: ours}, nil
	case ours != "":
		return hook{state: hookViaTool, copy: ours}, nil
	case setAside && !same:
		return hook{state: hookTaken}, nil
	}
	return hook{state: hookOther}, nil
}

// states reads every hook terma installs in the repository at gitDir; false when the
// hooks directory or a hook cannot be read.
func states(gitDir string) (dir string, hooks map[string]hook, ok bool) {
	dir, _, err := hooksDirFor(gitDir)
	if err != nil {
		return "", nil, false
	}
	hooks = map[string]hook{}
	for _, name := range names {
		h, err := stateOf(dir, name)
		if err != nil {
			return "", nil, false
		}
		hooks[name] = h
	}
	return dir, hooks, true
}

// Looped reports whether pre-commit's hook and terma's run each other in the repository at
// gitDir, so every commit fails until the next install.
func Looped(gitDir string) bool {
	_, hooks, ok := states(gitDir)
	if !ok {
		return false
	}
	for _, h := range hooks {
		if h.state == hookLooped {
			return true
		}
	}
	return false
}

// HooksPathScope is where the core.hooksPath keeping git from .git/hooks is set: "worktree",
// "repository" or "global"; "" when git reads .git/hooks.
func HooksPathScope(gitDir string) string {
	// git uses the worktree's value, then the repository's, then the global one.
	local, worktree := gitx.HooksPathFS(gitDir)
	value, scope := worktree, "worktree"
	if value == "" {
		value, scope = local, "repository"
	}
	if value == "" {
		value, scope = gitx.GlobalHooksPathFS(), "global"
	}
	if value == "" || readsOwnHooks(gitDir, value) {
		return ""
	}
	return scope
}

// readsOwnHooks reports whether the core.hooksPath value names the repository's own hooks
// directory; git takes a relative one from the working tree it runs the hooks in.
func readsOwnHooks(gitDir, value string) bool {
	_, common, err := hooksDirFor(gitDir)
	if err != nil {
		return false
	}
	path := value
	if rest, ok := strings.CutPrefix(path, "~/"); ok {
		path = filepath.Join(os.Getenv("HOME"), rest) // git expands ~ from $HOME
	}
	if !filepath.IsAbs(path) {
		root := worktreeRoot(gitDir)
		if root == "" {
			return false
		}
		path = filepath.Join(root, path)
	}
	// Compare the directories holding them by identity: the hooks directory may not exist
	// yet, and the path may differ in case or go through a symlink.
	path = filepath.Clean(path)
	if filepath.Base(path) != hooksDir {
		return false
	}
	a, errA := os.Stat(filepath.Dir(path))
	b, errB := os.Stat(common)
	return errA == nil && errB == nil && os.SameFile(a, b)
}

// worktreeRoot is where git runs gitDir's hooks: a linked worktree's own checkout (from its
// gitdir file), the main one's, or "" for a bare repository.
func worktreeRoot(gitDir string) string {
	if gitx.CommonDirFS(gitDir) == filepath.Clean(gitDir) {
		if filepath.Base(gitDir) != ".git" {
			return ""
		}
		return filepath.Dir(filepath.Clean(gitDir))
	}
	data, err := os.ReadFile(filepath.Join(gitDir, "gitdir"))
	if err != nil {
		return ""
	}
	dotGit := strings.TrimSpace(string(data))
	if !filepath.IsAbs(dotGit) {
		dotGit = filepath.Join(gitDir, dotGit)
	}
	return filepath.Dir(filepath.Clean(dotGit))
}
