// Code generated by weaver from semconv/registry with semconv/templates/go; DO NOT EDIT.

// Package semconv is terma's telemetry vocabulary, generated from its Weaver registry
// (semconv/registry): the attribute keys, event names and enum values terma sends.
package semconv

// SchemaVersion is terma.schema.version: the registry's major version, on every resource terma sends.
const SchemaVersion = "2"

// Attribute keys, terma's own and those it references from OpenTelemetry's registries.
const (
	// ErrorTypeKey is error.type: Describes a class of error the operation ended with.
	ErrorTypeKey = "error.type"
	// GenAIAgentNameKey is gen_ai.agent.name: Human-readable name of the GenAI agent provided by the application.
	GenAIAgentNameKey = "gen_ai.agent.name"
	// GenAIConversationCompactedKey is gen_ai.conversation.compacted: Indicates whether the effective conversation context used for this operation is a compacted view of a prior conversation.
	GenAIConversationCompactedKey = "gen_ai.conversation.compacted"
	// GenAIMainAgentNameKey is gen_ai.main_agent.name: The human-readable name of the top-level Generative AI agent in the process.
	GenAIMainAgentNameKey = "gen_ai.main_agent.name"
	// GenAIRequestModelKey is gen_ai.request.model: The name of the GenAI model a request is being made to.
	GenAIRequestModelKey = "gen_ai.request.model"
	// GenAIRequestReasoningLevelKey is gen_ai.request.reasoning.level: The reasoning or thinking effort level requested for a GenAI model.
	GenAIRequestReasoningLevelKey = "gen_ai.request.reasoning.level"
	// GenAIResponseModelKey is gen_ai.response.model: The name of the model that generated the response.
	GenAIResponseModelKey = "gen_ai.response.model"
	// GenAIToolCallArgumentsKey is gen_ai.tool.call.arguments: Parameters passed to the tool call.
	GenAIToolCallArgumentsKey = "gen_ai.tool.call.arguments"
	// GenAIToolCallIDKey is gen_ai.tool.call.id: The tool call identifier.
	GenAIToolCallIDKey = "gen_ai.tool.call.id"
	// GenAIToolNameKey is gen_ai.tool.name: Name of the tool utilized by the agent.
	GenAIToolNameKey = "gen_ai.tool.name"
	// GenAIToolTypeKey is gen_ai.tool.type: Type of the tool utilized by the agent
	GenAIToolTypeKey = "gen_ai.tool.type"
	// HostNameKey is host.name: Name of the host. On UNIX systems, it may contain what the hostname command returns, or the fully qualified hostname, or another name specified by the user.
	HostNameKey = "host.name"
	// MiradorProjectIDKey is mirador.project.id: The Mirador project the record is delivered to, the platform's routing key.
	MiradorProjectIDKey = "mirador.project.id"
	// ServiceNameKey is service.name: Logical name of the service.
	ServiceNameKey = "service.name"
	// ServiceVersionKey is service.version: The version string of the service component. The format is not defined by these conventions.
	ServiceVersionKey = "service.version"
	// SessionIDKey is session.id: A unique ID to identify a session.
	SessionIDKey = "session.id"
	// TermaAccountBillingTypeKey is terma.account.billing_type: The provider's word for how the account is billed.
	TermaAccountBillingTypeKey = "terma.account.billing_type"
	// TermaAccountExtraUsageEnabledKey is terma.account.extra_usage.enabled: Whether the account may spend past its plan.
	TermaAccountExtraUsageEnabledKey = "terma.account.extra_usage.enabled"
	// TermaAccountIDKey is terma.account.id: The provider's id for the account the session ran under.
	TermaAccountIDKey = "terma.account.id"
	// TermaAccountOrganizationIDKey is terma.account.organization.id: The provider's id for the account's organization.
	TermaAccountOrganizationIDKey = "terma.account.organization.id"
	// TermaAccountOrganizationTypeKey is terma.account.organization.type: The provider's word for the organization's kind.
	TermaAccountOrganizationTypeKey = "terma.account.organization.type"
	// TermaAccountPlanTypeKey is terma.account.plan_type: The provider's word for the account's plan.
	TermaAccountPlanTypeKey = "terma.account.plan_type"
	// TermaAccountSeatIDKey is terma.account.seat.id: An opaque id for one person's seat in a shared account.
	TermaAccountSeatIDKey = "terma.account.seat.id"
	// TermaAccountSeatTierKey is terma.account.seat_tier: The provider's word for the seat's tier.
	TermaAccountSeatTierKey = "terma.account.seat_tier"
	// TermaAccountStatusKey is terma.account.status: Whether the record names the account.
	TermaAccountStatusKey = "terma.account.status"
	// TermaAgentFullyIdleKey is terma.agent.fully_idle: Whether the agent had nothing left running when the turn ended.
	TermaAgentFullyIdleKey = "terma.agent.fully_idle"
	// TermaAgentIDKey is terma.agent.id: The id of a subagent run, scoped to its session.
	TermaAgentIDKey = "terma.agent.id"
	// TermaAgentNicknameKey is terma.agent.nickname: The name the agent gave a subagent.
	TermaAgentNicknameKey = "terma.agent.nickname"
	// TermaAgentParentIDKey is terma.agent.parent.id: The terma.agent.id, or the thread, that launched the subagent.
	TermaAgentParentIDKey = "terma.agent.parent.id"
	// TermaAgentPathKey is terma.agent.path: The agent's label for a subagent's place in its tree.
	TermaAgentPathKey = "terma.agent.path"
	// TermaApprovalPermissionModeKey is terma.approval.permission_mode: The agent's permission mode when it asked for approval.
	TermaApprovalPermissionModeKey = "terma.approval.permission_mode"
	// TermaApprovalReasonKey is terma.approval.reason: The agent's description of what an approval request asks to do.
	TermaApprovalReasonKey = "terma.approval.reason"
	// TermaCaptureGapKey is terma.capture.gap: Why an observation stream lost its ordering boundary.
	TermaCaptureGapKey = "terma.capture.gap"
	// TermaCaptureSurfaceKey is terma.capture.surface: The capture path the record came from.
	TermaCaptureSurfaceKey = "terma.capture.surface"
	// TermaCommitFileCountKey is terma.commit.file.count: How many files the commit changed.
	TermaCommitFileCountKey = "terma.commit.file.count"
	// TermaCommitFileStatsKey is terma.commit.file.stats: The commit's changes per file, at most 50 of them.
	TermaCommitFileStatsKey = "terma.commit.file.stats"
	// TermaCommitFileStatsReportedKey is terma.commit.file.stats_reported: How many files terma.commit.file.stats lists.
	TermaCommitFileStatsReportedKey = "terma.commit.file.stats_reported"
	// TermaCommitFileStatsTruncatedKey is terma.commit.file.stats_truncated: Whether terma.commit.file.stats left files out.
	TermaCommitFileStatsTruncatedKey = "terma.commit.file.stats_truncated"
	// TermaCommitLinesAddedKey is terma.commit.lines.added: Lines the commit added across its text files.
	TermaCommitLinesAddedKey = "terma.commit.lines.added"
	// TermaCommitLinesDeletedKey is terma.commit.lines.deleted: Lines the commit deleted across its text files.
	TermaCommitLinesDeletedKey = "terma.commit.lines.deleted"
	// TermaCommitMessageSourceKey is terma.commit.message_source: Where git took the commit message from, as prepare-commit-msg reports it.
	TermaCommitMessageSourceKey = "terma.commit.message_source"
	// TermaCommitSessionCountKey is terma.commit.session.count: How many sessions are stamped into the commit.
	TermaCommitSessionCountKey = "terma.commit.session.count"
	// TermaCommitSessionIDsKey is terma.commit.session.ids: The sessions stamped into the commit.
	TermaCommitSessionIDsKey = "terma.commit.session.ids"
	// TermaCommitStagedCountKey is terma.commit.staged.count: How many files were staged when the message was stamped.
	TermaCommitStagedCountKey = "terma.commit.staged.count"
	// TermaCompactionItemIDKey is terma.compaction.item.id: The agent's id for the compaction item.
	TermaCompactionItemIDKey = "terma.compaction.item.id"
	// TermaCompactionTriggerKey is terma.compaction.trigger: What started a compaction.
	TermaCompactionTriggerKey = "terma.compaction.trigger"
	// TermaContextTokensKey is terma.context.tokens: The tokens the context held.
	TermaContextTokensKey = "terma.context.tokens"
	// TermaContextUsedPercentKey is terma.context.used_percent: How full the context was, from 0 to 100.
	TermaContextUsedPercentKey = "terma.context.used_percent"
	// TermaContextWindowSizeKey is terma.context.window_size: The context window's size, in tokens.
	TermaContextWindowSizeKey = "terma.context.window_size"
	// TermaCreditsBalanceKey is terma.credits.balance: The account's credit balance, a decimal in the provider's own unit.
	TermaCreditsBalanceKey = "terma.credits.balance"
	// TermaCreditsPresentKey is terma.credits.present: Whether the account has credits.
	TermaCreditsPresentKey = "terma.credits.present"
	// TermaCreditsUnlimitedKey is terma.credits.unlimited: Whether the account's credits are unlimited.
	TermaCreditsUnlimitedKey = "terma.credits.unlimited"
	// TermaEvidenceSourceKey is terma.evidence.source: Where the evidence the record carries was read, named by the agent's package.
	TermaEvidenceSourceKey = "terma.evidence.source"
	// TermaEvidenceStatusKey is terma.evidence.status: Whether the evidence could be read, so missing data never reads as zero.
	TermaEvidenceStatusKey = "terma.evidence.status"
	// TermaExecutionNumberKey is terma.execution.number: The agent's execution counter.
	TermaExecutionNumberKey = "terma.execution.number"
	// TermaFilesPathsKey is terma.files.paths: Repository-relative paths the session wrote.
	TermaFilesPathsKey = "terma.files.paths"
	// TermaFundingStatusKey is terma.funding.status: Whether the record carries who paid for the session.
	TermaFundingStatusKey = "terma.funding.status"
	// TermaHookEventKey is terma.hook.event: The agent hook that produced the record.
	TermaHookEventKey = "terma.hook.event"
	// TermaInvocationInitialStepsKey is terma.invocation.initial_steps: How many steps the conversation held when the invocation began.
	TermaInvocationInitialStepsKey = "terma.invocation.initial_steps"
	// TermaInvocationNumberKey is terma.invocation.number: The agent's invocation counter.
	TermaInvocationNumberKey = "terma.invocation.number"
	// TermaLoopCountKey is terma.loop.count: How many agent loops the run took.
	TermaLoopCountKey = "terma.loop.count"
	// TermaMainAgentVersionKey is terma.main_agent.version: The version of the agent named by gen_ai.main_agent.name.
	TermaMainAgentVersionKey = "terma.main_agent.version"
	// TermaMessageCountKey is terma.message.count: How many messages the run exchanged.
	TermaMessageCountKey = "terma.message.count"
	// TermaMessageIDKey is terma.message.id: The agent's id for the message.
	TermaMessageIDKey = "terma.message.id"
	// TermaMessagePhaseKey is terma.message.phase: The agent's label for where in the turn the message was said.
	TermaMessagePhaseKey = "terma.message.phase"
	// TermaMessageTextKey is terma.message.text: What the message said.
	TermaMessageTextKey = "terma.message.text"
	// TermaMessageTruncatedKey is terma.message.truncated: Whether terma.message.text was cut at terma's bound.
	TermaMessageTruncatedKey = "terma.message.truncated"
	// TermaModelParamContextKey is terma.model_param.context: The context setting the developer selected for the model.
	TermaModelParamContextKey = "terma.model_param.context"
	// TermaModelParamThinkingKey is terma.model_param.thinking: The thinking setting the developer selected for the model.
	TermaModelParamThinkingKey = "terma.model_param.thinking"
	// TermaObservationIDKey is terma.observation.id: The replay-stable id of one observation.
	TermaObservationIDKey = "terma.observation.id"
	// TermaObservationSequenceKey is terma.observation.sequence: The observation's position in its stream.
	TermaObservationSequenceKey = "terma.observation.sequence"
	// TermaObservationStreamKey is terma.observation.stream: The ordered stream the observation belongs to; a new stream marks a lost ordering boundary.
	TermaObservationStreamKey = "terma.observation.stream"
	// TermaObservationTimeKey is terma.observation.time: When the provider wrote what was observed, RFC 3339 in UTC.
	TermaObservationTimeKey = "terma.observation.time"
	// TermaOperationDurationMsKey is terma.operation.duration_ms: How long the operation took, in milliseconds.
	TermaOperationDurationMsKey = "terma.operation.duration_ms"
	// TermaOperationDurationStatusKey is terma.operation.duration_status: Why terma.operation.duration_ms is absent when the agent sent one.
	TermaOperationDurationStatusKey = "terma.operation.duration_status"
	// TermaOperationInterruptedKey is terma.operation.interrupted: Whether the failed operation was interrupted by the developer.
	TermaOperationInterruptedKey = "terma.operation.interrupted"
	// TermaOperationStatusKey is terma.operation.status: How the operation the event records ended.
	TermaOperationStatusKey = "terma.operation.status"
	// TermaProviderSessionIDKey is terma.provider.session.id: The agent's own session id, where it differs from the session.id terma files the record under.
	TermaProviderSessionIDKey = "terma.provider.session.id"
	// TermaPushCommitCountKey is terma.push.commit.count: How many commits the push sent; exact below 10000, at least 10000 otherwise.
	TermaPushCommitCountKey = "terma.push.commit.count"
	// TermaPushCommitsKey is terma.push.commits: The full ids of the commits the push sent, newest first, at most 500 of them.
	TermaPushCommitsKey = "terma.push.commits"
	// TermaPushCommitsTruncatedKey is terma.push.commits_truncated: Whether terma.push.commits left commits out.
	TermaPushCommitsTruncatedKey = "terma.push.commits_truncated"
	// TermaPushForcedKey is terma.push.forced: Whether the push replaced commits the remote branch had, as a force-push does.
	TermaPushForcedKey = "terma.push.forced"
	// TermaPushIDKey is terma.push.id: One pushed ref of one push, so a record sent twice can be counted once.
	TermaPushIDKey = "terma.push.id"
	// TermaPushLocalRefKey is terma.push.local.ref: What was pushed, as git names it to pre-push.
	TermaPushLocalRefKey = "terma.push.local.ref"
	// TermaPushNewRevisionKey is terma.push.new.revision: The commit id the push set the remote branch to.
	TermaPushNewRevisionKey = "terma.push.new.revision"
	// TermaPushOldRevisionKey is terma.push.old.revision: The remote branch's commit id before the push; omitted for a new branch.
	TermaPushOldRevisionKey = "terma.push.old.revision"
	// TermaPushRangeKey is terma.push.range: How terma.push.commits was worked out.
	TermaPushRangeKey = "terma.push.range"
	// TermaPushRemoteNameKey is terma.push.remote.name: The configured remote the push went to.
	TermaPushRemoteNameKey = "terma.push.remote.name"
	// TermaPushRemoteRefKey is terma.push.remote.ref: The full name of the branch the push updated on the remote.
	TermaPushRemoteRefKey = "terma.push.remote.ref"
	// TermaPushRemoteURLKey is terma.push.remote.url: The URL the push went to, without credentials.
	TermaPushRemoteURLKey = "terma.push.remote.url"
	// TermaPushSessionIDsKey is terma.push.session.ids: The sessions stamped into the commits terma.push.commits lists.
	TermaPushSessionIDsKey = "terma.push.session.ids"
	// TermaPushStatusKey is terma.push.status: What the local repository showed about the push's outcome.
	TermaPushStatusKey = "terma.push.status"
	// TermaQuotaStatusKey is terma.quota.status: Whether the record carries the session's quota.
	TermaQuotaStatusKey = "terma.quota.status"
	// TermaRateLimitFiveHourResetsAtKey is terma.rate_limit.five_hour.resets_at: When the five-hour window resets, in Unix seconds.
	TermaRateLimitFiveHourResetsAtKey = "terma.rate_limit.five_hour.resets_at"
	// TermaRateLimitFiveHourUsedPercentKey is terma.rate_limit.five_hour.used_percent: How much of the five-hour window is used, from 0 to 100.
	TermaRateLimitFiveHourUsedPercentKey = "terma.rate_limit.five_hour.used_percent"
	// TermaRateLimitPrimaryResetsAtKey is terma.rate_limit.primary.resets_at: When the primary window resets, in Unix seconds.
	TermaRateLimitPrimaryResetsAtKey = "terma.rate_limit.primary.resets_at"
	// TermaRateLimitPrimaryUsedPercentKey is terma.rate_limit.primary.used_percent: How much of the provider's primary window is used, from 0 to 100.
	TermaRateLimitPrimaryUsedPercentKey = "terma.rate_limit.primary.used_percent"
	// TermaRateLimitPrimaryWindowMinutesKey is terma.rate_limit.primary.window_minutes: The primary window's length, in minutes.
	TermaRateLimitPrimaryWindowMinutesKey = "terma.rate_limit.primary.window_minutes"
	// TermaRateLimitReachedTypeKey is terma.rate_limit.reached_type: The provider's word for the limit the account reached.
	TermaRateLimitReachedTypeKey = "terma.rate_limit.reached_type"
	// TermaRateLimitSecondaryResetsAtKey is terma.rate_limit.secondary.resets_at: When the secondary window resets, in Unix seconds.
	TermaRateLimitSecondaryResetsAtKey = "terma.rate_limit.secondary.resets_at"
	// TermaRateLimitSecondaryUsedPercentKey is terma.rate_limit.secondary.used_percent: How much of the provider's secondary window is used, from 0 to 100.
	TermaRateLimitSecondaryUsedPercentKey = "terma.rate_limit.secondary.used_percent"
	// TermaRateLimitSecondaryWindowMinutesKey is terma.rate_limit.secondary.window_minutes: The secondary window's length, in minutes.
	TermaRateLimitSecondaryWindowMinutesKey = "terma.rate_limit.secondary.window_minutes"
	// TermaRateLimitSevenDayResetsAtKey is terma.rate_limit.seven_day.resets_at: When the seven-day window resets, in Unix seconds.
	TermaRateLimitSevenDayResetsAtKey = "terma.rate_limit.seven_day.resets_at"
	// TermaRateLimitSevenDayUsedPercentKey is terma.rate_limit.seven_day.used_percent: How much of the seven-day window is used, from 0 to 100.
	TermaRateLimitSevenDayUsedPercentKey = "terma.rate_limit.seven_day.used_percent"
	// TermaRateLimitSpendLimitResetsAtKey is terma.rate_limit.spend_limit.resets_at: When the spend limit resets, in Unix seconds.
	TermaRateLimitSpendLimitResetsAtKey = "terma.rate_limit.spend_limit.resets_at"
	// TermaRateLimitSpendLimitUsedPercentKey is terma.rate_limit.spend_limit.used_percent: How much of the spend limit is used, from 0 to 100.
	TermaRateLimitSpendLimitUsedPercentKey = "terma.rate_limit.spend_limit.used_percent"
	// TermaRelayAttributionKey is terma.relay.attribution: How the relay found the part's session when the part did not name it.
	TermaRelayAttributionKey = "terma.relay.attribution"
	// TermaRelayHeartbeatReasonKey is terma.relay.heartbeat.reason: Why the relay sent a heartbeat.
	TermaRelayHeartbeatReasonKey = "terma.relay.heartbeat.reason"
	// TermaRelaySessionIDKey is terma.relay.session.id: The session the relay inferred for a part that named none.
	TermaRelaySessionIDKey = "terma.relay.session.id"
	// TermaRepositoryRootKey is terma.repository.root: The absolute path of the working tree the session or the git operation ran in.
	TermaRepositoryRootKey = "terma.repository.root"
	// TermaSchemaVersionKey is terma.schema.version: The version of this registry the record follows.
	TermaSchemaVersionKey = "terma.schema.version"
	// TermaSessionParentIDKey is terma.session.parent.id: The session that opened this one for a subagent.
	TermaSessionParentIDKey = "terma.session.parent.id"
	// TermaSessionTitleKey is terma.session.title: The name the agent gave the session.
	TermaSessionTitleKey = "terma.session.title"
	// TermaSpendControlReachedKey is terma.spend_control.reached: Whether the account reached its spend control.
	TermaSpendControlReachedKey = "terma.spend_control.reached"
	// TermaStepIndexKey is terma.step.index: The step's index in its conversation, which only grows.
	TermaStepIndexKey = "terma.step.index"
	// TermaTerminationReasonKey is terma.termination.reason: The agent's word for why the turn ended.
	TermaTerminationReasonKey = "terma.termination.reason"
	// TermaToolCallCountKey is terma.tool_call.count: How many tool calls the run made.
	TermaToolCallCountKey = "terma.tool_call.count"
	// TermaTurnIDKey is terma.turn.id: The turn the event belongs to, in the agent's own id.
	TermaTurnIDKey = "terma.turn.id"
	// TermaUsageCacheReadTokensKey is terma.usage.cache_read_tokens: Cache-read input tokens as the agent reported them, in a snapshot rather than per call.
	TermaUsageCacheReadTokensKey = "terma.usage.cache_read_tokens"
	// TermaUsageCacheWriteTokensKey is terma.usage.cache_write_tokens: Cache-write input tokens as the agent reported them, in a snapshot rather than per call.
	TermaUsageCacheWriteTokensKey = "terma.usage.cache_write_tokens"
	// TermaUsageInputTokensKey is terma.usage.input_tokens: Input tokens as the agent reported them.
	TermaUsageInputTokensKey = "terma.usage.input_tokens"
	// TermaUsageOutputTokensKey is terma.usage.output_tokens: Output tokens as the agent reported them, in a snapshot rather than per call.
	TermaUsageOutputTokensKey = "terma.usage.output_tokens"
	// TermaUsageScopeKey is terma.usage.scope: What the record's usage counts cover.
	TermaUsageScopeKey = "terma.usage.scope"
	// TermaUsageSemanticsKey is terma.usage.semantics: How the record's usage counts add up.
	TermaUsageSemanticsKey = "terma.usage.semantics"
	// TermaUsageStatusKey is terma.usage.status: Whether the record's usage counts were reported.
	TermaUsageStatusKey = "terma.usage.status"
	// TermaVersionKey is terma.version: The version of terma whose relay received the part from the agent.
	TermaVersionKey = "terma.version"
	// TermaWorkingDirectoryKey is terma.working_directory: The absolute path of the directory the session's agent hooks last ran in.
	TermaWorkingDirectoryKey = "terma.working_directory"
	// UserEmailKey is user.email: User email address.
	UserEmailKey = "user.email"
	// VCSOwnerNameKey is vcs.owner.name: The group owner within the version control system.
	VCSOwnerNameKey = "vcs.owner.name"
	// VCSProviderNameKey is vcs.provider.name: The name of the version control system provider.
	VCSProviderNameKey = "vcs.provider.name"
	// VCSRefHeadNameKey is vcs.ref.head.name: The name of the [reference](https://git-scm.com/docs/gitglossary#def_ref) such as **branch** or **tag** in the repository.
	VCSRefHeadNameKey = "vcs.ref.head.name"
	// VCSRefHeadRevisionKey is vcs.ref.head.revision: The revision, literally [revised version](https://www.merriam-webster.com/dictionary/revision), The revision most often refers to a commit object in Git, or a revision number in SVN.
	VCSRefHeadRevisionKey = "vcs.ref.head.revision"
	// VCSRefHeadTypeKey is vcs.ref.head.type: The type of the [reference](https://git-scm.com/docs/gitglossary#def_ref) in the repository.
	VCSRefHeadTypeKey = "vcs.ref.head.type"
	// VCSRepositoryNameKey is vcs.repository.name: The human readable name of the repository. It SHOULD NOT include any additional identifier like Group/SubGroup in GitLab or organization in GitHub.
	VCSRepositoryNameKey = "vcs.repository.name"
	// VCSRepositoryURLFullKey is vcs.repository.url.full: The [canonical URL](https://support.google.com/webmasters/answer/10347851) of the repository providing the complete HTTP(S) address in order to locate and identify the repository through a browser.
	VCSRepositoryURLFullKey = "vcs.repository.url.full"
)

// Event names, carried in each log record's EventName field.
const (
	// TermaApprovalRequestedEvent is terma.approval.requested: The agent asked the developer for approval; whether it was given is not reported.
	TermaApprovalRequestedEvent = "terma.approval.requested"
	// TermaAssistantMessageEvent is terma.assistant.message: One reply from an agent whose export leaves its replies out; content as a whole.
	TermaAssistantMessageEvent = "terma.assistant.message"
	// TermaCommitEvent is terma.commit: A commit stamped with sessions was made.
	TermaCommitEvent = "terma.commit"
	// TermaCommitStampedEvent is terma.commit.stamped: prepare-commit-msg stamped sessions into a commit message.
	TermaCommitStampedEvent = "terma.commit.stamped"
	// TermaCommitUnattributedEvent is terma.commit.unattributed: A commit no session was stamped into, counted but never its files.
	TermaCommitUnattributedEvent = "terma.commit.unattributed"
	// TermaCompactionEvent is terma.compaction: The agent compacted the conversation.
	TermaCompactionEvent = "terma.compaction"
	// TermaFilesTouchedEvent is terma.files.touched: A session wrote files in the repository.
	TermaFilesTouchedEvent = "terma.files.touched"
	// TermaPushEvent is terma.push: A branch was pushed, one event per branch the push updated.
	TermaPushEvent = "terma.push"
	// TermaRelayHeartbeatEvent is terma.relay.heartbeat: The relay is running; sent with service.name terma-relay.
	TermaRelayHeartbeatEvent = "terma.relay.heartbeat"
	// TermaSessionAccountEvent is terma.session.account: The account state the session's agent holds.
	TermaSessionAccountEvent = "terma.session.account"
	// TermaSessionCaptureEvent is terma.session.capture: How a capture is going, kept apart from what it captured.
	TermaSessionCaptureEvent = "terma.session.capture"
	// TermaSessionEndEvent is terma.session.end: A session ended.
	TermaSessionEndEvent = "terma.session.end"
	// TermaSessionLimitEvent is terma.session.limit: A turn failed on a typed provider limit.
	TermaSessionLimitEvent = "terma.session.limit"
	// TermaSessionObservationEvent is terma.session.observation: One hook-derived snapshot of a session's state, never an additive counter.
	TermaSessionObservationEvent = "terma.session.observation"
	// TermaSessionQuotaEvent is terma.session.quota: The provider's rate-limit windows for the session, as last observed.
	TermaSessionQuotaEvent = "terma.session.quota"
	// TermaSessionStartEvent is terma.session.start: A session started, or an agent that reports no start named its session at a turn's end.
	TermaSessionStartEvent = "terma.session.start"
	// TermaSessionTitleEvent is terma.session.title: The name an agent gave a session; a rename is a new event. Content as a whole.
	TermaSessionTitleEvent = "terma.session.title"
	// TermaSubagentCallEvent is terma.subagent.call: The parent's view of the tool call that launched a subagent; it says nothing of spend.
	TermaSubagentCallEvent = "terma.subagent.call"
	// TermaSubagentEndEvent is terma.subagent.end: A subagent's run, or one of its turns, ended.
	TermaSubagentEndEvent = "terma.subagent.end"
	// TermaSubagentStartEvent is terma.subagent.start: A subagent started inside its parent's session.
	TermaSubagentStartEvent = "terma.subagent.start"
	// TermaToolCallEvent is terma.tool.call: One tool call, keyed on its call id, which is its replay identity.
	TermaToolCallEvent = "terma.tool.call"
)

// Enum values.
const (
	// ErrorTypeOther is error.type _OTHER: A fallback error value to be used when the instrumentation doesn't define a custom value.
	ErrorTypeOther = "_OTHER"
	// TermaCaptureGapInvalidCheckpoint is terma.capture.gap invalid_checkpoint: The ordering checkpoint was unreadable, so a new stream began.
	TermaCaptureGapInvalidCheckpoint = "invalid_checkpoint"
	// TermaCaptureSurfaceDesktop is terma.capture.surface desktop: Records only terma reports for the agent, sent from every surface.
	TermaCaptureSurfaceDesktop = "desktop"
	// TermaCommitMessageSourceMessage is terma.commit.message_source message: The message came from -m or -F.
	TermaCommitMessageSourceMessage = "message"
	// TermaCommitMessageSourceTemplate is terma.commit.message_source template: The message came from a template.
	TermaCommitMessageSourceTemplate = "template"
	// TermaCommitMessageSourceCommit is terma.commit.message_source commit: The message came from an existing commit (-c, -C or --amend).
	TermaCommitMessageSourceCommit = "commit"
	// TermaCompactionTriggerAuto is terma.compaction.trigger auto: The agent compacted on its own.
	TermaCompactionTriggerAuto = "auto"
	// TermaCompactionTriggerManual is terma.compaction.trigger manual: The developer asked for it.
	TermaCompactionTriggerManual = "manual"
	// TermaOperationDurationStatusInvalid is terma.operation.duration_status invalid: The agent reported a duration that is not a non-negative integer.
	TermaOperationDurationStatusInvalid = "invalid"
	// TermaPushRangeUpdate is terma.push.range update: The commits in the new revision and not the old one, exactly.
	TermaPushRangeUpdate = "update"
	// TermaPushRangeNewBranch is terma.push.range new_branch: A new branch: the commits in the new revision that no branch of the remote had, as the local remote-tracking branches showed before the push.
	TermaPushRangeNewBranch = "new_branch"
	// TermaPushRangeFallback is terma.push.range fallback: The commits in the new revision that no remote-tracking branch had before the push, of any remote for a push to a URL: the old commit is not in the local repository, or there is no remote to go by, so they may include commits the remote already had.
	TermaPushRangeFallback = "fallback"
	// TermaPushStatusTrackingRefUpdated is terma.push.status tracking_ref_updated: Once git push exited, the remote-tracking branch had moved to the new revision, which git does only for a ref the remote accepted.
	TermaPushStatusTrackingRefUpdated = "tracking_ref_updated"
	// TermaPushStatusUnknown is terma.push.status unknown: No evidence either way: the push was rejected, was a dry run, outlasted the wait, or has no remote-tracking branch terma can read.
	TermaPushStatusUnknown = "unknown"
	// TermaRelayAttributionCatchAll is terma.relay.attribution catch-all: Global mode placed the part in its default project.
	TermaRelayAttributionCatchAll = "catch-all"
	// TermaRelayAttributionProcess is terma.relay.attribution process: The part named no session; its process named one.
	TermaRelayAttributionProcess = "process"
	// TermaRelayHeartbeatReasonStart is terma.relay.heartbeat.reason start: The relay started.
	TermaRelayHeartbeatReasonStart = "start"
	// TermaRelayHeartbeatReasonInterval is terma.relay.heartbeat.reason interval: The heartbeat period passed.
	TermaRelayHeartbeatReasonInterval = "interval"
	// TermaRelayHeartbeatReasonSetup is terma.relay.heartbeat.reason setup: Setup finished; the platform reads it as installed and working.
	TermaRelayHeartbeatReasonSetup = "setup"
	// TermaUsageScopeParentTurn is terma.usage.scope parent_turn: The parent conversation's turn, subagents excluded.
	TermaUsageScopeParentTurn = "parent_turn"
	// TermaUsageSemanticsSnapshot is terma.usage.semantics snapshot: A repeated snapshot, never an additive delta.
	TermaUsageSemanticsSnapshot = "snapshot"
	// TermaUsageStatusAvailable is terma.usage.status available: Every count was reported.
	TermaUsageStatusAvailable = "available"
	// TermaUsageStatusPartial is terma.usage.status partial: Some counts were reported.
	TermaUsageStatusPartial = "partial"
	// TermaUsageStatusUnavailable is terma.usage.status unavailable: No count was reported.
	TermaUsageStatusUnavailable = "unavailable"
	// TermaUsageStatusInvalid is terma.usage.status invalid: A count was not a non-negative integer.
	TermaUsageStatusInvalid = "invalid"
	// VCSProviderNameGithub is vcs.provider.name github: [GitHub](https://github.com)
	VCSProviderNameGithub = "github"
	// VCSProviderNameGitlab is vcs.provider.name gitlab: [GitLab](https://gitlab.com)
	VCSProviderNameGitlab = "gitlab"
	// VCSProviderNameGitea is vcs.provider.name gitea: [Gitea](https://gitea.io)
	VCSProviderNameGitea = "gitea"
	// VCSProviderNameBitbucket is vcs.provider.name bitbucket: [Bitbucket](https://bitbucket.org)
	VCSProviderNameBitbucket = "bitbucket"
	// VCSRefHeadTypeBranch is vcs.ref.head.type branch: [branch](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefbranchabranch)
	VCSRefHeadTypeBranch = "branch"
	// VCSRefHeadTypeTag is vcs.ref.head.type tag: [tag](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddeftagatag)
	VCSRefHeadTypeTag = "tag"
)
